io:
	gcc io.c
	a.out

ioCPP:
	g++ io.cpp
	a.out

primitiveStringC:
	g++ primitiveString.C
	a.out

primitiveStringCC:
	g++ primitiveString.cc
	a.out

primitiveStringCPP:
	g++ primitiveString.cpp
	a.out

array: 
	g++ -o arrayExample arrayExample.cpp
	./arrayExample

card: 
	g++ -o cardExample cardExample.cpp
	./cardExample

clean:
	rm *.o
	rm cardExample


